version: "3"
services:
  database:
    container_name: database
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    build:
      context: .
      dockerfile: docker/database.dockerfile
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: database
        target: /var/lib/postgresql/data

  # redis:
  #   container_name: redis
  #   image: redis:latest
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - type: volume
  #       source: redis_data
  #       target: /data

volumes:
  database:
  # redis_data: