# Generated by Django 4.2 on 2024-06-28 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Directory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ref_id", models.CharField(blank=True, max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "directory_type",
                    models.CharField(
                        choices=[("custom", "Custom"), ("default", "Default")],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
