# Generated by Django 4.2 on 2024-06-28 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_id"),
        ("directories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directory",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="directories",
                to="users.user",
            ),
        ),
    ]
