# Generated by Django 4.2 on 2024-06-28 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("directories", "0002_alter_directory_user"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="directory",
            table="directories",
        ),
    ]
