# Generated by Django 4.2 on 2024-06-19 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0002_alter_user_last_login"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("red_id", models.CharField(max_length=200, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "active"),
                            ("inactive", "inactive"),
                            ("deleted", "deleted"),
                        ],
                        default="active",
                        max_length=50,
                    ),
                ),
                (
                    "attached_docs_status",
                    models.CharField(
                        choices=[
                            ("uploading", "uploading"),
                            ("completed", "completed"),
                        ],
                        default="uploading",
                        max_length=50,
                    ),
                ),
                ("private_url", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("extension_type", models.CharField(max_length=10)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("user_input", "user_input"),
                            ("generated_output", "generated_output"),
                            ("document_attachment", "document_attachment"),
                        ],
                        default="user_input",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        db_column="parent_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="documents.document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "documents",
            },
        ),
    ]
