# Generated by Django 4.2 on 2024-06-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="text_content",
            field=models.TextField(null=True),
        ),
    ]
