# Generated by Django 4.2 on 2024-06-19 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_document_text_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="parent",
            field=models.ForeignKey(
                db_column="parent_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="documents.document",
            ),
        ),
    ]
