# Generated by Django 4.2 on 2024-06-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_sessions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersession",
            old_name="user",
            new_name="user_id",
        ),
        migrations.AddField(
            model_name="usersession",
            name="access_token",
            field=models.CharField(default=None, max_length=200),
        ),
    ]
