# Generated by Django 4.2 on 2024-06-18 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("user_sessions", "0002_rename_user_usersession_user_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersession",
            name="user_id",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="users.user",
            ),
        ),
    ]
