# Generated by Django 4.2 on 2024-06-18 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_sessions", "0003_alter_usersession_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersession",
            old_name="user_id",
            new_name="user",
        ),
    ]
